version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: meu-banco
    volumes:
      - ./db_data:/var/lib/postgresql/data

  backend-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VARIABLE_1: valor_1
      VARIABLE_2: valor_2
    depends_on:
      - db
    ports:
      - "8000:8000"  # Mapeia a porta do host para a porta do backend no container
